name: Test

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - README.md
      - LICENSE
      - "*.md"
      - .gitignore
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md
      - LICENSE
      - "*.md"
      - .gitignore
  workflow_dispatch:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [macos, ios, maccatalyst, visionos]
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Select Xcode 26
      run: sudo xcode-select -s /Applications/Xcode_26.1.app

    - name: Build
      run: make build-${{ matrix.platform }}
      continue-on-error: ${{ matrix.platform == 'maccatalyst' || matrix.platform == 'visionos' }}

    - name: Test
      run: make test-${{ matrix.platform }}
      continue-on-error: ${{ matrix.platform == 'maccatalyst' || matrix.platform == 'visionos' }}
